[package]
name = "logitech-led"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]

[target.'cfg(windows)'.dependencies]
logitech-led-sys = {path = "logitech-led-sys"}
widestring = "0.2.2"

[dependencies]
winapi = "0.2.8"