[package]
name = "logi-led-sys"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]
description = "Rust FFI bindings for the Logitech LED SDK."
links = "LogitechLed"
build = "build.rs"

[build-dependencies]
winreg = "0.4"
